module.exports = {
  ethics: process.env.channel_ethics,
  events: process.env.channel_events,
  general: process.env.channel_general,
  help: process.env.channel_help,
  ideas: process.env.channel_ideas,
  jobs: process.env.channel_jobs,
  logs: process.env.channel_logs,
  moderators: process.env.channel_moderators,
  news: process.env.channel_news,
  projects: process.env.channel_projects,
  testing: process.env.channel_testing,
  testing_private: process.env.channel_testing_private,
  tools_resources: process.env.channel_tools_resources,
  twitter_feed: process.env.channel_twitter_feed,
};
